- hosts: testservers_ota
   tasks:
   - name: updates a server
     become: true
     apt: update_cache=yes
   - name: upgrade a server without touching wget
     become: true
     apt: upgrade=dist
     name: wget
     state: present
