- hosts: testservers_ota
   ansible_become: true
   
   tasks: 
   - name: Marking package for hold
     command: mark-hold wget
         
   - name: updates a server
     apt: update_cache=yes
          
   - name: upgrade a server without touching wget
     apt: upgrade=dist
         
   - name: Unmarking package from hold
     command: mark-hold wget
